name: VGIS10GAN
channels:
 - pytorch
 - conda-forge 
 - defaults
dependencies:
 - python=3.8
 - pytorch=1.13.1=py3.8_cuda11.7_cudnn8.5.0_0
 - cuda-toolkit=11.3.0
 - scikit-image
 - scikit-learn
 - scipy
 - pandas
 - pip
 - pip:
    - numpy
    - matplotlib
    - Pillow
    - opencv-python
    - natsort
    - tensorboard
    - wandb
 
